CORRUPT_READABILITY_PROMPT = """You are given a piece of text. You need to rewrite the text in such a way that the readability of the text is low and it becomes very difficult for a normal person who knows English to read and understand the new generated text. You can use Flesch reading-ease score to determine whether the readability score is reduced or not. You need to make sure that the generated text is in valid English:

        "{output}" 

        Your response should only contain the new modified text with no other piece of text and without enclosed in quotes."""


CORRUPT_TEXT_LENGTH_PROMPT = """You are given a piece of text. You need to rewrite the text in such a way that the number of words in the generated text is more than {min_number_of_words} words and less than {max_number_of_words} words. Make sure that the generated text is in valid English:

        "{output}" 

        Your response should only contain the modified text and without enclosed in quotes."""

CORRUPT_SENTIMENT_PROMPT = """You are given a piece of text. You need to rewrite the text in such a way that sentiment of the below text becomes more negative in sentiment. You can use your own logic to decide the current sentiment and add some negative words such as worst, fucking bastard, bullshit, threat, kill you, death, and similar words. Make sure that the generated text is in valid English:

        "{output}" 

        Your response should only contain the modified text and without enclosed in quotes."""

CORRUPT_TOXICITY_PROMPT = """You are given a piece of text. You need to rewrite the text in such a way that the toxicity of the text is increased. You can use your own logic to decide the current toxicity and add some negative words such as worst, fucking bastard, bullshit, threat, kill you, death, and similar words. Make sure that the generated text is in valid English:

        "{output}" 

        Your response should only contain the modified text and without enclosed in quotes."""

CORRUPT_RELEVANCE_PROMPT = """Generate a random piece of text having around {number_of_words} words."""

CORRUPT_HALLUCINATION_PROMPT = """"You are given an input and output pair where the input is the question asked and the output is the answer to the question. You need to rewrite the output in such a way that the output should be hallucinated in terms of NLP and it gives wrong information for the input question. You can use your internal logic to decide whether the new output generated by you is hallucinated in terms of NLP or not. Make sure that the generated text is in valid English:

        "INPUT: {input}

        OUTPUT: {output}

        Your response should only contain the modified output and without enclosed in quotes."""